### ISSUE TITLE
Strange exception

### ISSUE THREAD

**Issue by ul** [weavejester/cljfmt#5]
I get this trying to run `lein cljfmt check` over my source tree:

```
ul@cybercraft ~/V/vion> lein cljfmt check
java.lang.UnsupportedOperationException: null
 at rewrite_clj.node.comment.CommentNode.sexpr (comment.clj:6)
    rewrite_clj.node$value.invoke (node.clj:116)
    rewrite_clj.zip.base$value.invoke (base.clj:56)
    cljfmt.core$inner_indent.invoke (core.clj:100)
    cljfmt.core$eval2847$fn__2849$fn__2851.invoke (core.clj:132)
    clojure.core$some_fn$sp2__6490.invoke (core.clj:6800)
    clojure.core$some_fn$spn__6527$fn__6528.invoke (core.clj:6817)
    clojure.core$some.invoke (core.clj:2515)
    clojure.core$some_fn$spn__6527.invoke (core.clj:6817)
    cljfmt.core$indent_amount.invoke (core.clj:143)
    cljfmt.core$indent_line.invoke (core.clj:147)
    cljfmt.core$indent$fn__2870.invoke (core.clj:154)
    cljfmt.core$edit_all.invoke (core.clj:12)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:626)
    cljfmt.core$transform.doInvoke (core.clj:16)
    clojure.lang.RestFn.invoke (RestFn.java:464)
    cljfmt.core$indent.invoke (core.clj:154)
    cljfmt.core$reindent.invoke (core.clj:157)
    cljfmt.core$reformat_form.doInvoke (core.clj:167)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    cljfmt.core$reformat_string.doInvoke (core.clj:170)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    leiningen.cljfmt$reformat_string.invoke (cljfmt.clj:23)
    leiningen.cljfmt$valid_format_QMARK_.invoke (cljfmt.clj:27)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$partial$fn__4228.doInvoke (core.clj:2468)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$complement$fn__4082.invoke (core.clj:1370)
    clojure.core$filter$fn__4264.invoke (core.clj:2605)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:484)
    clojure.core$seq.invoke (core.clj:133)
    clojure.core$empty_QMARK_.invoke (core.clj:5706)
    leiningen.cljfmt$check.doInvoke (cljfmt.clj:58)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    leiningen.cljfmt$check.invoke (cljfmt.clj:54)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invoke (core.clj:626)
    leiningen.cljfmt$cljfmt.doInvoke (cljfmt.clj:79)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:626)
    leiningen.core.main$partial_task$fn__6094.doInvoke (main.clj:263)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    leiningen.core.main$apply_task.invoke (main.clj:313)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:319)
    leiningen.core.main$_main$fn__6160.invoke (main.clj:392)
    leiningen.core.main$_main.doInvoke (main.clj:385)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    clojure.lang.Var.invoke (Var.java:394)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

Some individual files are checked successfully, thus generally plugin is working. How do I determine problematic files if not trying to run check on every file individually?

**Comment by ul** [comment]
ran check over all files one by one, will post problematic files soon

**Comment by ul** [comment]
here two kinds of errors: https://gist.github.com/ul/4e9dbebc89d0b5f5de1f

**Comment by weavejester** [comment]
Thanks for the report, this might have something to do with mishandling of comments, which I'm currently looking into fixing.

**Comment by weavejester** [comment]
The comments should be fixed in master, and I'll release 0.1.2 soon.

However, the keyword error looks like a problem in your source code, as `:register/error/username` isn't a valid Clojure keyword. Keywords and symbols can only have `/` once, so your keyword should read: `:register.error/username`.

**Comment by ul** [comment]
Thank you, will check if `tower` works with dotted notation and switch to it if yes.

**Comment by ul** [comment]
Still getting errors with 0.1.2, problematic files: https://gist.github.com/ul/c00795c23feb59f07b51

**Comment by weavejester** [comment]
Thanks for the report!

It looks like the first error is caused by the symbol `v'`, which is allowed by the Clojure reader, but rewrite-clj falls over on. The Clojure language definition and the edn spec both say that a `'` is not a valid symbol character, so maybe rewrite-clj is correct in this instance.

The second issue is definitely a bug. I'm looking into it and should have a fix eventually. Thanks for your time in reporting this.

**Comment by ul** [comment]
Thank you about pointing out `'` gotcha, fixed it in my sources.

**Comment by weavejester** [comment]
I've just released version 0.1.3, which fixes the comment bug and a few others. Let me know if it works out for you.

**Comment by ul** [comment]
Yes! Works like a charm! Thank you for the great tool!

P. S. Is Boot support planned?

**Comment by weavejester** [comment]
I don't plan on working on a Boot version myself, but because cljfmt is split into a standalone library and Leiningen plugin, it shouldn't be difficult to support Boot.

**Comment by escherize** [comment]
In case anyone else lands here from googling boot cljfmt, here's a link where the author does what @weavejester just described:

https://gist.github.com/bartojs/851e5103b517549236dd
